/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { type GLTF } from "three-stdlib";
import { useLookAtMouse } from "../../hooks/useLookAtMouse";
import { useCharacterAnimations } from "../../hooks/useCharacterAnimations";

type GLTFResult = GLTF & {
  nodes: {
    ["tripo_node_82d1a1d4-dfbd-4112-bc95-b15e6d7c24a8"]: THREE.SkinnedMesh;
    ["mixamorigHips"]: THREE.Bone;
    ["mixamorigHead"]: THREE.Bone;
  };
  materials: {
    ["tripo_mat_82d1a1d4-dfbd-4112-bc95-b15e6d7c24a8"]: THREE.MeshStandardMaterial;
  };
};

type ModelProps = React.JSX.IntrinsicElements["group"] & {
  followMouse?: boolean;
};

export function Model(props: ModelProps) {
  const group = useRef<THREE.Group>(null);

  const { nodes, materials, animations } = useGLTF(
    "/models/character.glb",
  ) as unknown as GLTFResult;

  useCharacterAnimations(animations, group, "idle.001");

  useLookAtMouse(nodes.mixamorigHead, props.followMouse);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <skinnedMesh
            name="tripo_node_82d1a1d4-dfbd-4112-bc95-b15e6d7c24a8"
            geometry={
              nodes["tripo_node_82d1a1d4-dfbd-4112-bc95-b15e6d7c24a8"].geometry
            }
            material={
              materials["tripo_mat_82d1a1d4-dfbd-4112-bc95-b15e6d7c24a8"]
            }
            skeleton={
              nodes["tripo_node_82d1a1d4-dfbd-4112-bc95-b15e6d7c24a8"].skeleton
            }
          />
          <primitive object={nodes["mixamorigHips"]} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/character.glb");
