/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useMemo, useRef } from "react";

import { useGLTF } from "@react-three/drei";
import { type GLTF } from "three-stdlib";
import { clone } from "three/examples/jsm/utils/SkeletonUtils.js";

import { useLookAtMouse } from "../../hooks/useLookAtMouse";

import {
  useCharacterAnimations,
  type ActionName,
} from "../../hooks/useCharacterAnimations";

type GLTFResult = GLTF & {
  nodes: {
    ["tripo_node_82d1a1d4-dfbd-4112-bc95-b15e6d7c24a8"]: THREE.SkinnedMesh;
    ["mixamorigHips"]: THREE.Bone;
    ["mixamorigHead"]: THREE.Bone;
  };

  materials: {
    ["tripo_mat_82d1a1d4-dfbd-4112-bc95-b15e6d7c24a8"]: THREE.MeshStandardMaterial;
  };
};

type ModelProps = React.JSX.IntrinsicElements["group"] & {
  followMouse?: boolean;
  activeAction?: ActionName;
  onModelClick?: () => void;
  onAnimationFinished?: () => void;
};

export function Model({
  followMouse = true,
  activeAction = "idle.001",
  onModelClick,
  onAnimationFinished,
  ...props
}: ModelProps) {
  /*
   * Grupo externo responsável apenas por:
   *
   * position
   * rotation
   * scale
   * eventos
   */
  const group = useRef<THREE.Group>(null);

  /*
   * O useGLTF continua utilizando cache.
   *
   * A diferença é que não vamos utilizar
   * diretamente os bones/skeleton compartilhados.
   */
  const { scene, materials, animations } = useGLTF(
    "/models/character.glb",
  ) as unknown as GLTFResult;

  /*
   * Cria uma cópia independente da hierarquia
   * completa do personagem.
   *
   * SkeletonUtils.clone também clona corretamente
   * Bones e Skeleton de SkinnedMesh.
   */
  const clonedScene = useMemo(() => {
    return clone(scene);
  }, [scene]);

  /*
   * Busca a cabeça dentro da cópia independente.
   *
   * A validação também garante para o TypeScript
   * que clonedHead é obrigatoriamente THREE.Bone.
   */
  const clonedHead = useMemo(() => {
    const head = clonedScene.getObjectByName("mixamorigHead");

    if (!(head instanceof THREE.Bone)) {
      throw new Error('Bone "mixamorigHead" não encontrado no personagem.');
    }

    return head;
  }, [clonedScene]);

  /*
   * Configuração do material.
   */
  useEffect(() => {
    const material =
      materials["tripo_mat_82d1a1d4-dfbd-4112-bc95-b15e6d7c24a8"];

    material.roughness = 0.5;
    material.metalness = 0;
    material.envMapIntensity = 0;

    material.roughnessMap = null;
    material.metalnessMap = null;

    material.needsUpdate = true;
  }, [materials]);

  /*
   * Aplica sombras aos meshes existentes
   * dentro da cópia do personagem.
   */
  useEffect(() => {
    clonedScene.traverse((object) => {
      if (object instanceof THREE.Mesh || object instanceof THREE.SkinnedMesh) {
        object.castShadow = true;
      }
    });
  }, [clonedScene]);

  /*
   * IMPORTANTE:
   *
   * A animação agora é vinculada diretamente
   * à clonedScene dessa instância.
   *
   * Hero:
   * clonedScene A + mixer A
   *
   * Technologies:
   * clonedScene B + mixer B
   */
  useCharacterAnimations(
    animations,
    clonedScene,
    activeAction,
    onAnimationFinished,
  );

  /*
   * Usa a cabeça pertencente à própria cópia.
   *
   * Hero:
   * followMouse={true}
   *
   * Technologies:
   * followMouse={false}
   */
  useLookAtMouse(clonedHead, followMouse);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      onClick={(event) => {
        event.stopPropagation();

        onModelClick?.();
      }}
    >
      <primitive object={clonedScene} />
    </group>
  );
}

useGLTF.preload("/models/character.glb");
