/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { type GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["tripo_node_16c0409e-117c-4420-9f41-05866d811578"]: THREE.SkinnedMesh;
    Root: THREE.Bone;
  };
  materials: {
    ["tripo_mat_16c0409e-117c-4420-9f41-05866d811578"]: THREE.MeshStandardMaterial;
  };
};

type ActionName = "walk";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Model(props: React.JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/models/character.glb",
  ) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group) as unknown as {
    
    actions: GLTFActions;
  };

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <skinnedMesh
            name="tripo_node_16c0409e-117c-4420-9f41-05866d811578"
            geometry={
              nodes["tripo_node_16c0409e-117c-4420-9f41-05866d811578"].geometry
            }
            material={
              materials["tripo_mat_16c0409e-117c-4420-9f41-05866d811578"]
            }
            skeleton={
              nodes["tripo_node_16c0409e-117c-4420-9f41-05866d811578"].skeleton
            }
          />
          <primitive object={nodes.Root} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/character.glb");
